settings:
  react:
    version: 'detect'
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended  
  - standard-with-typescript
overrides: []
parserOptions:
  project: ["tsconfig.json"]
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  {
    "@typescript-eslint/no-misused-promises":["error", { "checksVoidReturn": false }],
  }
